{{- if .Values.podDisruptionBudget -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "algolia-search-api.fullname" . }}
  labels:
    {{- include "algolia-search-api.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "algolia-search-api.selectorLabels" . | nindent 6 }}
{{ toYaml .Values.podDisruptionBudget | indent 2 }}
{{- end -}}
